default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PG_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("PG_PORT") { '5445' } %>
  username: <%= ENV.fetch("PG_USER") { 'postgres' } %>
  password: <%= ENV.fetch("PG_PASSWORD") { 'password' } %>

development:
  <<: *default
  database: test_chat_dev

test:
  <<: *default
  database: test_chat_

production:
  <<: *default
  database: production
